
// This file has been generated by the GUI designer. Do not modify.
namespace hm
{
	public partial class home
	{
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		private global::Gtk.VBox vbox1;
		private global::Gtk.HBox hbox2;
		private global::Gtk.Image image326;
		private global::Gtk.Image image325;
		private global::Gtk.Image image324;
		private global::Gtk.Expander expander1;
		private global::Gtk.VBox vbox2;
		private global::Gtk.Button button3;
		private global::Gtk.Button button4;
		private global::Gtk.Button button8;
		private global::Gtk.Label GtkLabel2;
		private global::Gtk.Button button5;
		private global::Gtk.Expander expander2;
		private global::Gtk.VBox vbox3;
		private global::Gtk.Button button6;
		private global::Gtk.Label GtkLabel5;
		private global::Gtk.Button button7;
		private global::Gtk.Expander expander4;
		private global::Gtk.VBox vbox4;
		private global::Gtk.Expander expander7;
		private global::Gtk.Table table3;
		private global::Gtk.Label label13;
		private global::Gtk.Label label14;
		private global::Gtk.Label label15;
		private global::Gtk.Label label16;
		private global::Gtk.Label label17;
		private global::Gtk.Label label18;
		private global::Gtk.Label GtkLabel7;
		private global::Gtk.Expander expander8;
		private global::Gtk.VBox vbox5;
		private global::Gtk.Label label19;
		private global::Gtk.Label label20;
		private global::Gtk.Label label21;
		private global::Gtk.Label GtkLabel8;
		private global::Gtk.Label GtkLabel9;
		private global::Gtk.HBox hbox1;
		private global::Gtk.Button button1;
		private global::Gtk.Button button2;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget hm.home
			this.Name = "hm.home";
			this.Title = global::Mono.Unix.Catalog.GetString ("Home");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.AllowShrink = true;
			this.DefaultWidth = 500;
			this.DefaultHeight = 600;
			// Container child hm.home.Gtk.Container+ContainerChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			global::Gtk.Viewport w1 = new global::Gtk.Viewport ();
			w1.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child GtkViewport.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.image326 = new global::Gtk.Image ();
			this.image326.Name = "image326";
			this.image326.Pixbuf = new global::Gdk.Pixbuf (global::System.IO.Path.Combine (global::System.AppDomain.CurrentDomain.BaseDirectory, "./nurse.ico"));
			this.hbox2.Add (this.image326);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.image326]));
			w2.Position = 0;
			// Container child hbox2.Gtk.Box+BoxChild
			this.image325 = new global::Gtk.Image ();
			this.image325.Name = "image325";
			this.image325.Pixbuf = new global::Gdk.Pixbuf (global::System.IO.Path.Combine (global::System.AppDomain.CurrentDomain.BaseDirectory, "./Hospital-red-icon.png"));
			this.hbox2.Add (this.image325);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.image325]));
			w3.Position = 1;
			w3.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.image324 = new global::Gtk.Image ();
			this.image324.Name = "image324";
			this.image324.Pixbuf = new global::Gdk.Pixbuf (global::System.IO.Path.Combine (global::System.AppDomain.CurrentDomain.BaseDirectory, "./doctor.ico"));
			this.hbox2.Add (this.image324);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.image324]));
			w4.Position = 2;
			w4.Fill = false;
			this.vbox1.Add (this.hbox2);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox2]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.expander1 = new global::Gtk.Expander (null);
			this.expander1.CanFocus = true;
			this.expander1.Name = "expander1";
			this.expander1.Expanded = true;
			// Container child expander1.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.button3 = new global::Gtk.Button ();
			this.button3.CanFocus = true;
			this.button3.Name = "button3";
			// Container child button3.Gtk.Container+ContainerChild
			global::Gtk.Alignment w6 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w7 = new global::Gtk.HBox ();
			w7.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w8 = new global::Gtk.Image ();
			w8.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "stock_certificate", global::Gtk.IconSize.LargeToolbar);
			w7.Add (w8);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w10 = new global::Gtk.Label ();
			w10.LabelProp = global::Mono.Unix.Catalog.GetString ("Register Patient");
			w7.Add (w10);
			w6.Add (w7);
			this.button3.Add (w6);
			this.vbox2.Add (this.button3);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.button3]));
			w14.Position = 0;
			// Container child vbox2.Gtk.Box+BoxChild
			this.button4 = new global::Gtk.Button ();
			this.button4.CanFocus = true;
			this.button4.Name = "button4";
			this.button4.UseUnderline = true;
			// Container child button4.Gtk.Container+ContainerChild
			global::Gtk.Alignment w15 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w16 = new global::Gtk.HBox ();
			w16.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w17 = new global::Gtk.Image ();
			w17.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-find", global::Gtk.IconSize.LargeToolbar);
			w16.Add (w17);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w19 = new global::Gtk.Label ();
			w19.LabelProp = global::Mono.Unix.Catalog.GetString ("Search Patient");
			w19.UseUnderline = true;
			w16.Add (w19);
			w15.Add (w16);
			this.button4.Add (w15);
			this.vbox2.Add (this.button4);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.button4]));
			w23.Position = 1;
			w23.Expand = false;
			w23.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.button8 = new global::Gtk.Button ();
			this.button8.CanFocus = true;
			this.button8.Name = "button8";
			this.button8.UseUnderline = true;
			// Container child button8.Gtk.Container+ContainerChild
			global::Gtk.Alignment w24 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w25 = new global::Gtk.HBox ();
			w25.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w26 = new global::Gtk.Image ();
			w26.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "stock_notes", global::Gtk.IconSize.LargeToolbar);
			w25.Add (w26);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w28 = new global::Gtk.Label ();
			w28.LabelProp = global::Mono.Unix.Catalog.GetString ("Calculate Bill");
			w28.UseUnderline = true;
			w25.Add (w28);
			w24.Add (w25);
			this.button8.Add (w24);
			this.vbox2.Add (this.button8);
			global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.button8]));
			w32.Position = 2;
			w32.Expand = false;
			w32.Fill = false;
			this.expander1.Add (this.vbox2);
			this.GtkLabel2 = new global::Gtk.Label ();
			this.GtkLabel2.Name = "GtkLabel2";
			this.GtkLabel2.LabelProp = global::Mono.Unix.Catalog.GetString ("Patient Records");
			this.GtkLabel2.UseUnderline = true;
			this.expander1.LabelWidget = this.GtkLabel2;
			this.vbox1.Add (this.expander1);
			global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.expander1]));
			w34.Position = 1;
			w34.Expand = false;
			w34.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.button5 = new global::Gtk.Button ();
			this.button5.CanFocus = true;
			this.button5.Name = "button5";
			this.button5.UseUnderline = true;
			// Container child button5.Gtk.Container+ContainerChild
			global::Gtk.Alignment w35 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w36 = new global::Gtk.HBox ();
			w36.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w37 = new global::Gtk.Image ();
			w37.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-file", global::Gtk.IconSize.LargeToolbar);
			w36.Add (w37);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w39 = new global::Gtk.Label ();
			w39.LabelProp = global::Mono.Unix.Catalog.GetString ("Generate Bill");
			w39.UseUnderline = true;
			w36.Add (w39);
			w35.Add (w36);
			this.button5.Add (w35);
			this.vbox1.Add (this.button5);
			global::Gtk.Box.BoxChild w43 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.button5]));
			w43.Position = 2;
			w43.Expand = false;
			w43.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.expander2 = new global::Gtk.Expander (null);
			this.expander2.CanFocus = true;
			this.expander2.Name = "expander2";
			this.expander2.Expanded = true;
			// Container child expander2.Gtk.Container+ContainerChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.button6 = new global::Gtk.Button ();
			this.button6.CanFocus = true;
			this.button6.Name = "button6";
			this.button6.UseUnderline = true;
			// Container child button6.Gtk.Container+ContainerChild
			global::Gtk.Alignment w44 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w45 = new global::Gtk.HBox ();
			w45.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w46 = new global::Gtk.Image ();
			w46.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-find", global::Gtk.IconSize.LargeToolbar);
			w45.Add (w46);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w48 = new global::Gtk.Label ();
			w48.LabelProp = global::Mono.Unix.Catalog.GetString ("Search Staff Member");
			w48.UseUnderline = true;
			w45.Add (w48);
			w44.Add (w45);
			this.button6.Add (w44);
			this.vbox3.Add (this.button6);
			global::Gtk.Box.BoxChild w52 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.button6]));
			w52.Position = 0;
			w52.Expand = false;
			w52.Fill = false;
			this.expander2.Add (this.vbox3);
			this.GtkLabel5 = new global::Gtk.Label ();
			this.GtkLabel5.Name = "GtkLabel5";
			this.GtkLabel5.Xalign = 1F;
			this.GtkLabel5.LabelProp = global::Mono.Unix.Catalog.GetString ("Staff Record");
			this.GtkLabel5.UseUnderline = true;
			this.expander2.LabelWidget = this.GtkLabel5;
			this.vbox1.Add (this.expander2);
			global::Gtk.Box.BoxChild w54 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.expander2]));
			w54.Position = 3;
			w54.Expand = false;
			w54.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.button7 = new global::Gtk.Button ();
			this.button7.CanFocus = true;
			this.button7.Name = "button7";
			this.button7.UseUnderline = true;
			// Container child button7.Gtk.Container+ContainerChild
			global::Gtk.Alignment w55 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w56 = new global::Gtk.HBox ();
			w56.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w57 = new global::Gtk.Image ();
			w57.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "stock_add-bookmark", global::Gtk.IconSize.LargeToolbar);
			w56.Add (w57);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w59 = new global::Gtk.Label ();
			w59.LabelProp = global::Mono.Unix.Catalog.GetString ("Add Staff Member");
			w59.UseUnderline = true;
			w56.Add (w59);
			w55.Add (w56);
			this.button7.Add (w55);
			this.vbox1.Add (this.button7);
			global::Gtk.Box.BoxChild w63 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.button7]));
			w63.Position = 4;
			w63.Expand = false;
			w63.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.expander4 = new global::Gtk.Expander (null);
			this.expander4.CanFocus = true;
			this.expander4.Name = "expander4";
			this.expander4.Expanded = true;
			// Container child expander4.Gtk.Container+ContainerChild
			this.vbox4 = new global::Gtk.VBox ();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.expander7 = new global::Gtk.Expander (null);
			this.expander7.CanFocus = true;
			this.expander7.Name = "expander7";
			// Container child expander7.Gtk.Container+ContainerChild
			this.table3 = new global::Gtk.Table (((uint)(6)), ((uint)(1)), true);
			this.table3.Name = "table3";
			this.table3.RowSpacing = ((uint)(6));
			this.table3.ColumnSpacing = ((uint)(6));
			// Container child table3.Gtk.Table+TableChild
			this.label13 = new global::Gtk.Label ();
			this.label13.Name = "label13";
			this.label13.LabelProp = global::Mono.Unix.Catalog.GetString ("Accident and emergency (A&E)");
			this.label13.Justify = ((global::Gtk.Justification)(1));
			this.table3.Add (this.label13);
			global::Gtk.Table.TableChild w64 = ((global::Gtk.Table.TableChild)(this.table3 [this.label13]));
			w64.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.label14 = new global::Gtk.Label ();
			this.label14.Name = "label14";
			this.label14.LabelProp = global::Mono.Unix.Catalog.GetString ("Anaesthetics");
			this.table3.Add (this.label14);
			global::Gtk.Table.TableChild w65 = ((global::Gtk.Table.TableChild)(this.table3 [this.label14]));
			w65.TopAttach = ((uint)(1));
			w65.BottomAttach = ((uint)(2));
			w65.XOptions = ((global::Gtk.AttachOptions)(4));
			w65.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.label15 = new global::Gtk.Label ();
			this.label15.Name = "label15";
			this.label15.LabelProp = global::Mono.Unix.Catalog.GetString ("Cardiology ");
			this.table3.Add (this.label15);
			global::Gtk.Table.TableChild w66 = ((global::Gtk.Table.TableChild)(this.table3 [this.label15]));
			w66.TopAttach = ((uint)(2));
			w66.BottomAttach = ((uint)(3));
			w66.XOptions = ((global::Gtk.AttachOptions)(4));
			w66.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.label16 = new global::Gtk.Label ();
			this.label16.Name = "label16";
			this.label16.LabelProp = global::Mono.Unix.Catalog.GetString ("Critical care");
			this.table3.Add (this.label16);
			global::Gtk.Table.TableChild w67 = ((global::Gtk.Table.TableChild)(this.table3 [this.label16]));
			w67.TopAttach = ((uint)(3));
			w67.BottomAttach = ((uint)(4));
			w67.XOptions = ((global::Gtk.AttachOptions)(4));
			w67.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.label17 = new global::Gtk.Label ();
			this.label17.Name = "label17";
			this.label17.LabelProp = global::Mono.Unix.Catalog.GetString ("Gynaecology");
			this.table3.Add (this.label17);
			global::Gtk.Table.TableChild w68 = ((global::Gtk.Table.TableChild)(this.table3 [this.label17]));
			w68.TopAttach = ((uint)(4));
			w68.BottomAttach = ((uint)(5));
			w68.XOptions = ((global::Gtk.AttachOptions)(4));
			w68.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.label18 = new global::Gtk.Label ();
			this.label18.Name = "label18";
			this.label18.LabelProp = global::Mono.Unix.Catalog.GetString ("Haematology");
			this.table3.Add (this.label18);
			global::Gtk.Table.TableChild w69 = ((global::Gtk.Table.TableChild)(this.table3 [this.label18]));
			w69.TopAttach = ((uint)(5));
			w69.BottomAttach = ((uint)(6));
			w69.XOptions = ((global::Gtk.AttachOptions)(4));
			w69.YOptions = ((global::Gtk.AttachOptions)(4));
			this.expander7.Add (this.table3);
			this.GtkLabel7 = new global::Gtk.Label ();
			this.GtkLabel7.Name = "GtkLabel7";
			this.GtkLabel7.LabelProp = global::Mono.Unix.Catalog.GetString ("Departments");
			this.GtkLabel7.UseUnderline = true;
			this.expander7.LabelWidget = this.GtkLabel7;
			this.vbox4.Add (this.expander7);
			global::Gtk.Box.BoxChild w71 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.expander7]));
			w71.Position = 0;
			w71.Expand = false;
			w71.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.expander8 = new global::Gtk.Expander (null);
			this.expander8.CanFocus = true;
			this.expander8.Name = "expander8";
			// Container child expander8.Gtk.Container+ContainerChild
			this.vbox5 = new global::Gtk.VBox ();
			this.vbox5.Name = "vbox5";
			this.vbox5.Spacing = 6;
			// Container child vbox5.Gtk.Box+BoxChild
			this.label19 = new global::Gtk.Label ();
			this.label19.Name = "label19";
			this.label19.LabelProp = global::Mono.Unix.Catalog.GetString ("Doctors");
			this.vbox5.Add (this.label19);
			global::Gtk.Box.BoxChild w72 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.label19]));
			w72.Position = 0;
			w72.Expand = false;
			w72.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.label20 = new global::Gtk.Label ();
			this.label20.Name = "label20";
			this.label20.LabelProp = global::Mono.Unix.Catalog.GetString ("Para-medical staff");
			this.vbox5.Add (this.label20);
			global::Gtk.Box.BoxChild w73 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.label20]));
			w73.Position = 1;
			w73.Expand = false;
			w73.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.label21 = new global::Gtk.Label ();
			this.label21.Name = "label21";
			this.label21.LabelProp = global::Mono.Unix.Catalog.GetString ("Non medical staff");
			this.vbox5.Add (this.label21);
			global::Gtk.Box.BoxChild w74 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.label21]));
			w74.Position = 2;
			w74.Expand = false;
			w74.Fill = false;
			this.expander8.Add (this.vbox5);
			this.GtkLabel8 = new global::Gtk.Label ();
			this.GtkLabel8.Name = "GtkLabel8";
			this.GtkLabel8.LabelProp = global::Mono.Unix.Catalog.GetString ("Staff Types");
			this.GtkLabel8.UseUnderline = true;
			this.expander8.LabelWidget = this.GtkLabel8;
			this.vbox4.Add (this.expander8);
			global::Gtk.Box.BoxChild w76 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.expander8]));
			w76.Position = 1;
			w76.Expand = false;
			w76.Fill = false;
			this.expander4.Add (this.vbox4);
			this.GtkLabel9 = new global::Gtk.Label ();
			this.GtkLabel9.Name = "GtkLabel9";
			this.GtkLabel9.LabelProp = global::Mono.Unix.Catalog.GetString ("Configuration");
			this.GtkLabel9.UseUnderline = true;
			this.expander4.LabelWidget = this.GtkLabel9;
			this.vbox1.Add (this.expander4);
			global::Gtk.Box.BoxChild w78 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.expander4]));
			w78.Position = 5;
			w78.Expand = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.button1 = new global::Gtk.Button ();
			this.button1.CanFocus = true;
			this.button1.Name = "button1";
			this.button1.UseUnderline = true;
			// Container child button1.Gtk.Container+ContainerChild
			global::Gtk.Alignment w79 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w80 = new global::Gtk.HBox ();
			w80.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w81 = new global::Gtk.Image ();
			w81.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-undo", global::Gtk.IconSize.LargeToolbar);
			w80.Add (w81);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w83 = new global::Gtk.Label ();
			w83.LabelProp = global::Mono.Unix.Catalog.GetString ("Sign Out");
			w83.UseUnderline = true;
			w80.Add (w83);
			w79.Add (w80);
			this.button1.Add (w79);
			this.hbox1.Add (this.button1);
			global::Gtk.Box.BoxChild w87 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.button1]));
			w87.Position = 0;
			// Container child hbox1.Gtk.Box+BoxChild
			this.button2 = new global::Gtk.Button ();
			this.button2.CanFocus = true;
			this.button2.Name = "button2";
			this.button2.UseUnderline = true;
			// Container child button2.Gtk.Container+ContainerChild
			global::Gtk.Alignment w88 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w89 = new global::Gtk.HBox ();
			w89.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w90 = new global::Gtk.Image ();
			w90.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-close", global::Gtk.IconSize.LargeToolbar);
			w89.Add (w90);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w92 = new global::Gtk.Label ();
			w92.LabelProp = global::Mono.Unix.Catalog.GetString ("Close");
			w92.UseUnderline = true;
			w89.Add (w92);
			w88.Add (w89);
			this.button2.Add (w88);
			this.hbox1.Add (this.button2);
			global::Gtk.Box.BoxChild w96 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.button2]));
			w96.Position = 1;
			this.vbox1.Add (this.hbox1);
			global::Gtk.Box.BoxChild w97 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
			w97.Position = 6;
			w97.Expand = false;
			w97.Fill = false;
			w1.Add (this.vbox1);
			this.GtkScrolledWindow.Add (w1);
			this.Add (this.GtkScrolledWindow);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Show ();
			this.button3.Clicked += new global::System.EventHandler (this.OnButton3Clicked);
			this.button4.Clicked += new global::System.EventHandler (this.OnButton4Clicked);
			this.button8.Clicked += new global::System.EventHandler (this.OnButton8Clicked);
			this.button5.Clicked += new global::System.EventHandler (this.OnButton5Clicked);
			this.button6.Clicked += new global::System.EventHandler (this.OnButton6Clicked);
			this.button7.Clicked += new global::System.EventHandler (this.OnButton7Clicked);
			this.button1.Clicked += new global::System.EventHandler (this.OnButton1Clicked);
			this.button2.Clicked += new global::System.EventHandler (this.OnButton2Clicked);
		}
	}
}
