
// This file has been generated by the GUI designer. Do not modify.
namespace hm
{
	public partial class PatientDetails
	{
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget hm.PatientDetails
			this.Name = "hm.PatientDetails";
			this.Title = global::Mono.Unix.Catalog.GetString ("PatientDetails");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show ();
		}
	}
}
